import fs from 'node:fs';import path from 'node:path';
import {startServer,launchPhoneBrowser,post,sleep,hook,input,Samples,killBoss,pressLand,waitForMode,installSignalHandlers,runCleanups} from '/private/tmp/claude-501/v14-qa/dev/v11-client/lib.mjs';
import {installSampler,resetSampler,readSampler,summarise} from '/private/tmp/claude-501/v14-qa/dev/v12-client/render/lib2.mjs';
const OUT='/Users/jaumepuig/Documents/growth-hackathon/dev/v14-qa';const result={at:new Date().toISOString(),description:'Full phone UI; 24 bots + one human; no screenshots during measurements. Travel skipped, real final shot and LAND.'};installSignalHandlers();
async function main(){
 const s=await startServer({port:8425,bots:24,env:{ASTRA_MOCK:'1',PERF_LOG:path.join(OUT,'logs/transition-perf.log'),V11_DRAWINGS_DIR:path.join(OUT,'data/transition-drawings')},logFile:path.join(OUT,'logs/transition-server.log')});
 const b=await launchPhoneBrowser(),{page}=await b.newPhone();await page.goto(s.base+'/controller.html?perf');await page.waitForFunction(()=>window.__spTest);await page.fill('#name','transition');await page.locator('#joinForm button').tap();await page.waitForFunction(()=>window.__sp.screen==='draw');await page.locator('#useDefault').tap();await page.waitForFunction(()=>window.__sp.game);await page.evaluate(()=>window.__game=window.__sp.game);
 await post(s.base,'/generate',{player:'transition',kind:'ship',image:Samples.dataUrl('ship',1),source:'draw',speculative:false});await post(s.base,'/start');await sleep(5000);
 const st=await hook.state(s.base),boss=st.boss;for(const player of Object.keys(st.players))await hook.teleport(s.base,{player,near:boss,distance:boss.radius+75,face:boss,heal:true});await sleep(1500);await installSampler(page);await resetSampler(page);
 await killBoss(s.base,'transition');await sleep(8000);let raw=await readSampler(page);result.bossKill=summarise(raw);result.bossKill.violations={calls:raw.calls.filter(n=>n>80).length,triangles:raw.tris.filter(n=>n>120000).length};fs.writeFileSync(path.join(OUT,'data/raw-phone-boss-kill-no-shots.json'),JSON.stringify(raw));
 await resetSampler(page);await pressLand(s.base,'transition');await waitForMode(s.base,'transition','planet');await sleep(5000);raw=await readSampler(page);result.landing=summarise(raw);result.landing.violations={calls:raw.calls.filter(n=>n>80).length,triangles:raw.tris.filter(n=>n>120000).length};fs.writeFileSync(path.join(OUT,'data/raw-phone-landing-no-shots.json'),JSON.stringify(raw));await b.browser.close();
}
main().catch(e=>{result.fatal=String(e.stack||e);}).finally(async()=>{fs.writeFileSync(path.join(OUT,'data/transition-perf.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));await runCleanups();process.exit(result.fatal?1:0);});
