import fs from 'node:fs';import path from 'node:path';
import {startServer,launchBig,launchPhoneBrowser,watchPage,post,sleep,hook,input,Samples,killBoss,pressLand,waitForMode,installSignalHandlers,runCleanups,summariseConsole} from '/Users/jaumepuig/Documents/growth-hackathon/dev/v14-test/scripts/lib.mjs';
import {serveHost,openHost,installSampler,resetSampler,readSampler,summarise} from '/Users/jaumepuig/Documents/growth-hackathon/dev/v14-test/scripts/lib2.mjs';
const OUT='/Users/jaumepuig/Documents/growth-hackathon/dev/v14-test';const device=process.argv[2]||'phone';
const fx=process.argv.includes('--effects');const suffix=fx?'-drawn-effects':'-drawn';
const result={at:new Date().toISOString(),device,staged:true,description:'25 planet actors + 25 parked ships. 24 bots moved to planet by QA-only hook (normally bots patrol space). Unique per-player v1.4 generated fallback specs for 25 ship3d ships +25 entity3d persons, one shared sample drawing; actual render.js.'};
installSignalHandlers();
async function main(){
const s=await startServer({port:8464,bots:24,script:path.join(OUT,'scripts/crowd-drawn-server.cjs'),env:{ASTRA_MOCK:'1',V11_DRAWINGS_DIR:path.join(OUT,'data/crowd-drawings'),PERF_LOG:path.join(OUT,'logs/crowd-perf-'+device+'.log')},logFile:path.join(OUT,'logs/crowd-server-'+device+'.log')});
await post(s.base,'/join',{player:'crowder',device:'crowder-qa-device'});await post(s.base,'/generate',{player:'crowder',kind:'ship',image:Samples.dataUrl('ship',1),source:'draw',speculative:false});await post(s.base,'/start',{countdown:false});await sleep(1000);await killBoss(s.base,'crowder');await pressLand(s.base,'crowder');await waitForMode(s.base,'crowder','planet');await post(s.base,'/__test/crowd');
let b,page,context;if(device==='tv'){const q=await launchBig();b=q.browser;page=q.page;context=q.context;}else{const q=await launchPhoneBrowser();b=q.browser;({page,context}=await q.newPhone());}
const sink=watchPage(page,device);await serveHost(context);await openHost(page,s.base,{screen:device==='tv'?'big':'phone',player:device==='phone'?'crowder':undefined});await sleep(6000);if(fx){await post(s.base,'/__test/effects');await sleep(1000);}await installSampler(page);await resetSampler(page);await sleep(25000);const raw=await readSampler(page);result.perf=summarise(raw);result.violations={calls:raw.calls.filter(n=>n>(device==='tv'?120:80)).length,triangles:device==='phone'?raw.tris.filter(n=>n>120000).length:null};result.state=await hook.state(s.base);result.console=summariseConsole([sink]);result.warningDetails=sink.warnings;result.render=await page.evaluate(()=>({perf:window.__game.perf(),models:window.__game._internals.game.island.explorers.size,parked:window.__game._internals.game.island.parked.size,drawn: [...window.__game._internals.game.island.explorers.values()].map(v=>({source:v.source,entity3d:v.model?.entity3d,kind:v.kind}))}));result.loadedEntity3d=result.render.drawn.filter(v=>v.entity3d).length; if(!result.loadedEntity3d) throw new Error('Invalid stress: no entity3d model loaded'); await page.screenshot({path:path.join(OUT,'shots/'+device+'-planet-crowded'+suffix+'.png')});fs.writeFileSync(path.join(OUT,'data/raw-'+device+'-planet-crowded'+suffix+'.json'),JSON.stringify(raw));await b.close();
}
main().catch(e=>{result.fatal=String(e.stack||e);}).finally(async()=>{fs.writeFileSync(path.join(OUT,'data/crowd-'+device+suffix+'.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({perf:result.perf,violations:result.violations,fatal:result.fatal}));await runCleanups();process.exit(result.fatal?1:0);});
