import fs from 'node:fs';import path from 'node:path';
import {startServer,launchBig,launchPhoneBrowser,watchPage,openEvents,post,sleep,hook,input,Samples,killBoss,pressLand,waitForMode,installSignalHandlers,runCleanups,summariseConsole} from '/Users/jaumepuig/Documents/growth-hackathon/dev/v19-codexfix/scripts/lib.mjs';
import {serveHost,openHost,installSampler,resetSampler,readSampler,summarise,installAttrib,resetAttrib,readAttrib,fixedBreakdown} from '/Users/jaumepuig/Documents/growth-hackathon/dev/v19-codexfix/scripts/lib2.mjs';
const OUT=process.env.OUT||'/Users/jaumepuig/Documents/growth-hackathon/dev/v19-codexfix';const device=process.argv[2]||'phone';
const fx=process.argv.includes('--effects');const suffix=fx?'-drawn-effects':'-drawn';
const result={at:new Date().toISOString(),device,staged:true,description:'25 planet actors + 25 parked ships. 25 human records placed by QA-only hooks (no bots). Unique per-player v1.4 generated fallback specs for 25 ship3d ships +25 entity3d persons, one shared sample drawing; actual render.js.'};
for(const d of ['data','logs','shots'])fs.mkdirSync(path.join(OUT,d),{recursive:true});
installSignalHandlers();
async function main(){
const s=await startServer({port:Number(process.env.PORT_RUN||8621),bots:0,script:path.join('/Users/jaumepuig/Documents/growth-hackathon/dev/v19-codexfix/scripts/','crowd-drawn-server.cjs'),env:{ASTRA_MOCK:'1',V11_DRAWINGS_DIR:path.join('/Users/jaumepuig/Documents/growth-hackathon/dev/v19-codexfix/data/crowd-drawings'),PERF_LOG:path.join(OUT,'logs/crowd-perf-'+device+'.log')},logFile:path.join(OUT,'logs/crowd-server-'+device+'.log')});
await post(s.base,'/join',{player:'crowder',device:'crowder-qa-device'});await post(s.base,'/generate',{player:'crowder',kind:'ship',image:Samples.dataUrl('ship',1),source:'draw',speculative:false});await post(s.base,'/__test/seed25',{});result.mode=(await post(s.base,'/mode',{minutes:4})).status;await post(s.base,'/start',{countdown:false});await sleep(1000);await killBoss(s.base,'crowder');await pressLand(s.base,'crowder');await waitForMode(s.base,'crowder','planet');await post(s.base,'/__test/crowd');
let b,page,context;if(device==='tv'){const q=await launchBig();b=q.browser;page=q.page;context=q.context;}else{const q=await launchPhoneBrowser();b=q.browser;({page,context}=await q.newPhone());}
const sink=watchPage(page,device);await serveHost(context);await openHost(page,s.base,{screen:device==='tv'?'big':'phone',player:device==='phone'?'crowder':undefined});await sleep(6000);if(fx){await post(s.base,'/__test/effects');await sleep(1000);}await installSampler(page);await installAttrib(page);await resetSampler(page);await resetAttrib(page);const nt=[];const stream=openEvents(s.base,m=>{if(m.type==='tick')nt.push({at:Date.now(),bytes:Buffer.byteLength(JSON.stringify(m)),players:m.players.length})});await sleep(25000);stream.close();result.network={ticks:nt.length,seconds:nt.length>1?(nt.at(-1).at-nt[0].at)/1000:0,maxBytes:Math.max(...nt.map(x=>x.bytes)),players:nt.at(-1)?.players};result.network.hz=(nt.length-1)/result.network.seconds;const raw=await readSampler(page);result.attrib=await readAttrib(page);result.fixed=await fixedBreakdown(page);result.perf=summarise(raw);result.violations={calls:raw.calls.filter(n=>n>(device==='tv'?120:80)).length,triangles:device==='phone'?raw.tris.filter(n=>n>120000).length:null};result.state=await hook.state(s.base);result.console=summariseConsole([sink]);result.warningDetails=sink.warnings;result.render=await page.evaluate(()=>({perf:window.__game.perf(),models:window.__game._internals.game.island.explorers.size,parked:window.__game._internals.game.island.parked.size,drawn: [...window.__game._internals.game.island.explorers.values()].map(v=>({source:v.source,entity3d:v.model?.entity3d,kind:v.kind}))}));result.loadedEntity3d=result.render.drawn.filter(v=>v.entity3d).length; if(!result.loadedEntity3d) throw new Error('Invalid stress: no entity3d model loaded'); await page.screenshot({path:path.join(OUT,'shots/'+device+'-planet-crowded'+suffix+'.png')});fs.writeFileSync(path.join(OUT,'data/raw-'+device+'-planet-crowded'+suffix+'.json'),JSON.stringify(raw));await b.close();
}
main().catch(e=>{result.fatal=String(e.stack||e);}).finally(async()=>{fs.writeFileSync(path.join(OUT,'data/crowd-'+device+suffix+'.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({perf:result.perf,violations:result.violations,fatal:result.fatal}));await runCleanups();process.exit(result.fatal?1:0);});
